name: WormholeXTremeWorlds
main: com.wormhole_xtreme.worlds.WormholeXTremeWorlds
version: 0.1
author: By alron
description: >
             Wormhole X-Treme Worlds! World management for Wormhole X-Treme!
             
commands:
  wxw:
    description: Manage Worlds via Wormhole X-Treme Worlds
    usage: |
            Travel Commands:
            /<command> [ go <world> | spawn ]
            Info Commands:
            /<command> [ list | info <world>]
            Admin Commands:
            /<command> [create | remove | modify | setspawn | connect] <args>